---
title: "Algorithms (Draft)"
date: "Compiled: `r Sys.Date()`"
output: pdf_document
header-includes:
  - \usepackage{algorithm2e}
  - \usepackage{amsmath}
---

# Curve Simulation

Notation and algorithm from the Bayesian prior simulation procedure by Brooks et al.:

\begin{algorithm}[H]

  \SetAlgoLined

  % Parameters
  \SetKw{empseas}{$s$}
  \SetKw{shape}{$f$}
  \SetKw{noise}{$\sigma$}
  \SetKw{pkht}{$\theta$}
  \SetKw{pacing}{$\nu$}
  \SetKw{numreps}{$R$}
  \SetKw{week}{$i$}

  % Parameter Descriptions
  \empseas{: empirical season} \BlankLine
  \shape{$\sim U\{\hat{f} : \text{historical season} s\}$} \BlankLine
  \noise{$\sim U\{ \hat{\tau}_s : \text{historical season} s$} \BlankLine
  \pkht{$\sim U \left[ \theta_m, \theta_M \right]$} \BlankLine
  \pacing{$\sim U \left[ 0.75, 1.25 \right]$} \BlankLine
  \numreps{: number of hypothetical seasons to Simulate} \BlankLine

  % Algorithm
  \ForEach{\empseas}{
    Fit $trendfilter(s) \rightarrow f(j)$\;
    \BlankLine

    \ForEach{\week where j = \week}{
      Calculate $\hat{\tau}^2_i = (y_{s,i} - \hat{f}_{s,j})^2$\;
    }
    \BlankLine
    Calculate $\hat{\tau}^2_s = { \genfrac {}{}{0pt}{0}{avg}{i} } \left( \hat{\tau}_i \right)$\;
  }
  \BlankLine

  \For{i = 1 to \numreps}{
    Draw $\left< \shape, \noise, \pkht, \nu \right>$\;
    Simulate curve as $f(i) + \epsilon, \text{ } \epsilon \sim N(0, \hat{\tau}^2_s)$\;
  }
\end{algorithm}


# Candidate Model Fitting

\begin{algorithm}[H]

  \SetAlgoLined

  % Parameters
  \SetKw{hihctrain}{$N_{train}$}  
  \SetKw{hihctest}{$N_{test}$}
  \SetKw{model}{$M$}
  \SetKw{varset}{$V$}
  \SetKw{outcomes}{$Y$}
  \SetKw{priorprd}{$k$}
  \SetKw{brep}{$B$}

  \SetKwFunction{ModelSelect}{ModelSelect}

  % Parameter Descriptions
  \hihctrain{: Size of training set }
  \BlankLine

  \hihctest{: Size of test set }
  \BlankLine

  \model{: Candidate model }
  \BlankLine

  \varset{: Variable set}
  \BlankLine

  \brep{: Number of bootstrap replicates}
  \BlankLine

  \outcomes{$\in$ \{peak hospitalizations, peak week, cumulative hospitalizations\} }
  \BlankLine\BlankLine


  % Algorithm

  $trainset$ $\leftarrow$ store half of simulated hypothetical hospitalization curves
  \BlankLine

  $testset$ $\leftarrow$ store other half of simulated hypothetical hospitalization curves
  \BlankLine

  \ForEach{\model}{

    Draw \brep of size \ $N_{train}$ from $trainset$.

    \ForEach{$b$ in \brep}{

      Run {\ModelSelect{\model, \varset, \brep, \text{AIC}, \text{backward stepwise}}};

      \ForEach{\outcomes}{
          Predict $\hat{Y}$ using \model\;
          Calculate root mean squared error and relative bias.
      }
    }
    Fit selected model from {\ModelSelect} to $testset$ \;

    \ForEach{\outcomes}{
      Predict $\hat{Y}$ using \model \;
      Calculate root mean squared error and relative bias.
    }
  }
  \BlankLine

\end{algorithm}
