sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=1 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=2 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=3 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=4 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=5 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=6 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=7 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=8 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=9 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=10 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=11 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=12 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=13 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=14 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkrate_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=15 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=1 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=2 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=3 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=4 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=5 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=6 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=7 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=8 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=9 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=10 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=11 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=12 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=13 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=14 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-pkweek_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=15 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=1 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=2 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=3 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=4 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=5 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=6 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=7 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=8 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=9 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=10 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=11 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=12 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=13 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=14 --mem=100GB 
sed -e 's/04_run_superlearner.R/12_ensemble-cv-1se.R/' RUN_TARGET-cumhosp_LAMBDA-lambda-1se.sh | sbatch --export=ALL,HOLDOUT_TEMPLATE=15 --mem=100GB 
